services:
  keycloak:
    container_name: kata_keycloak
    image: quay.io/keycloak/keycloak:26.0.5
    environment:
      - 'KEYCLOAK_ADMIN=admin'
      - 'KEYCLOAK_ADMIN_PASSWORD=admin'
    ports:
      - '8080:8080'
    command:
      - start-dev